importScripts('config.js');

chrome.runtime.onInstalled.addListener(() => {
  chrome.storage.local.get(['serverUrl', 'apiToken'], (result) => {
    let updates = {};
    const defaultServerUrl = (typeof DEFAULT_CONFIG !== 'undefined' && DEFAULT_CONFIG.serverUrl) || 'http://localhost:8000';
    const defaultApiToken = (typeof DEFAULT_CONFIG !== 'undefined' && DEFAULT_CONFIG.apiToken) || '';

    if (!result.serverUrl && defaultServerUrl) {
      updates.serverUrl = defaultServerUrl;
    }
    if (!result.apiToken && defaultApiToken) {
      updates.apiToken = defaultApiToken;
    }

    if (Object.keys(updates).length > 0) {
      chrome.storage.local.set(updates);
    }
  });
});

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === 'sync_cookies') {
    const serverUrl = request.serverUrl;
    
    // Fallback to saved apiToken in storage if not explicitly provided
    chrome.storage.local.get(['apiToken'], (result) => {
      const apiToken = request.apiToken || result.apiToken || '';
      
      // Get cookies for YouTube
      chrome.cookies.getAll({ domain: '.youtube.com' }, (cookies) => {
        if (!cookies || cookies.length === 0) {
          sendResponse({ success: false, error: 'No YouTube cookies found. Please log in or visit YouTube first.' });
          return;
        }

        // Convert cookies to Netscape format
        let netscapeFormat = "# Netscape HTTP Cookie File\n# http://curl.haxx.se/rfc/cookie_spec.html\n# Generated by DubbLM Cookie Sync\n\n";
        for (const cookie of cookies) {
          const domain = cookie.domain;
          const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
          const path = cookie.path;
          const secure = cookie.secure ? 'TRUE' : 'FALSE';
          const expiry = cookie.expirationDate ? Math.round(cookie.expirationDate) : 0;
          const name = cookie.name;
          const value = cookie.value;
          netscapeFormat += `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expiry}\t${name}\t${value}\n`;
        }

        // Convert format string to bytes/Blob-like format for backend upload
        const boundary = "----WebKitFormBoundaryDubbLMCookieSync" + Math.random().toString(36).substring(2);
        let body = `--${boundary}\r\n`;
        body += `Content-Disposition: form-data; name="file"; filename="cookies.txt"\r\n`;
        body += `Content-Type: text/plain\r\n\r\n`;
        body += netscapeFormat + `\r\n`;
        body += `--${boundary}--\r\n`;

        const arrayBuffer = new TextEncoder().encode(body);

        // Setup headers
        const headers = {
          'Content-Type': `multipart/form-data; boundary=${boundary}`
        };
        if (apiToken) {
          headers['Authorization'] = `Bearer ${apiToken}`;
        }

        // Post cookies to DubbLM server
        fetch(`${serverUrl}/api/v1/settings/cookies`, {
          method: 'POST',
          headers: headers,
          body: arrayBuffer
        })
        .then(response => {
          if (response.ok) {
            sendResponse({ success: true });
          } else {
            return response.text().then(text => {
              sendResponse({ success: false, error: `Server error: ${text}` });
            });
          }
        })
        .catch(err => {
          sendResponse({ success: false, error: `Connection failed: ${err.message}` });
        });
      });
    });

    return true; // Keeps the sendResponse channel open for async execution
  }
});
